---
title: "Résumé des principaux résultats scientifiques du projet FRB BioSceneMada"
# Document type
output: 
  pdf_document:
    citation_package: natbib
    fig_caption: true
    keep_tex: true
    latex_engine: pdflatex
# Authors
author: Ghislain Vieilledent
date: "`r format(Sys.time(), '%B %d, %Y')`"
# Text
#geometry: margin=1in
#fontfamily: mathpazo
#fontsize: 11pt
# PDF document
header-includes:
  - \hypersetup{colorlinks=true, citecolor=blue}
# Bibliography
bibliography: bib/biblio.bib
# csl: bib/journal-of-applied-ecology.csl
biblio-style: bib/jae.bst
---

# Rappel des objectifs du projet:

L'objectif du projet BioSceneMada est de fournir des scénarios d'évolution de la biodiversité sous l'impact conjoint du changement climatique et de la biodiversité à Madagascar. Suite aux trois premières années du projet concernant le volet scientifique, voici les principaux résultats que nous avons obtenus. Ces résultats seront consolidés et complétés pendant les deux dernières années du projet en parrallèle des activités de renforcement de capacité des institutions à Madagascar. Ces ateliers de renforcement de capacité permettront d'assurer le transfert des méthodes et outils scientifiques développés au cours des trois premières années du projet afin de déterminer des stratégies de conservation efficaces de la biodiversité.

# Principaux résultats scientifiques:

## 1. Carte de carbone forestier et vulnérabilité des forêts tropicales au changement climatique à Madagascar

Dans le cadre du projet BioSceneMada, en utilisant les données climatiques précédemment calculées (<https://madaclim.cirad.fr>) et des données d'inventaires forestiers pour 1771 placettes réparties sur l'ensemble de Madagascar, nous avons démontré qu'il existait un lien fort entre climat et stocks de carbone forestiers. Ce lien est notamment déterminé par les caractéristiques architecturales (hauteur notamment) des espèces d'arbres présentes le long du gradient climatique à Madagascar (climat --> assemblage d'espèces --> stocks de carbone). Ainsi, les stocks de carbone sont en moyenne beaucoup plus faibles en forêt épineuse (17 Mg.ha$^{-1}$) qu'en forêt humide (150 Mg.ha$^{-1}$). Le modèle statistique intégrant la relation climat-stock de carbone a permis de produire une carte précise des stocks de carbone forestier à Madagascar à une résolution de 250 m. Cette carte pourra être utilisée par les instances gouvernementales à Madagascar ou les porteurs de projet REDD+ au niveau régional pour le calcul des émissions de CO2 associées à la déforestation. Cette carte ainsi que les données qui ont permis de l'obtenir sont disponibles sur le site du projet BioSceneMada (<https://bioscenemada.cirad.fr/carbonmaps>) ainsi que sur le serveur de données Dryad (doi: [10.5061/dryad.9ph68](http://doi.org/10.5061/dryad.9ph68)).

Concernant les scénarios d'évolution de la biodiversité et des stocks de carbone forestier, nous avons montré à l'aide de ce modèle que les changements climatiques devraient induire des modifications fortes des communautés forestières et en conséquence une diminution de -17% (7-24%) des stocks de carbone forestier à Madagascar à l'horizon 2100 par rapport à 2010. Ces changements seront vraisemblablement plus forts pour la forêt humide de l'est (notamment autour de la péninsule de Masoala-Makira) que pour les forêts sèches et épineuses de l'ouest et du sud. En comparaison, un taux de déforestation constant de 0.5% par an conduirait à une perte de carbone forestier de l'ordre de 29% entre 2010 et 2100. L'impact potentiel des changements climatiques sur les émissions de CO2 n'est donc pas à négliger. Ces résultats ont été acceptés pour publication dans la revue _Journal of Ecology_ avec la référence ci-dessous. Les co-auteurs partenaires du projet sont soulignés:

**\underline{Vieilledent G.}, O. Gardi, \underline{C. Grinand}, C. Burren, M. Andriamanjato, C. Camara, C. J. Gardner, L. Glass, A. Rasolohery, H. Rakoto Ratsimba, V. Gond, \underline{J.-R. Rakotoarijaona}**. 2016. Bioclimatic envelope models predict a decrease in tropical forest carbon stocks with climate change in Madagascar. _Journal of Ecology_. **104**: 703-715. doi: [10.1111/1365-2745.12548](http://dx.doi.org/10.1111/1365-2745.12548).

Cet article a constitué le choix de l'éditeur pour le numéro **104**(3) de la revue Journal of Ecology: [Editor's Choice 104:3](https://jecologyblog.wordpress.com/2016/05/06/editors-choice-1043/).

Cet article a également été sélectionné par les éditeurs pour un numéro spécial de la revue Journal of Ecology intitulé "Plants in a changing world: global change and plant ecology". Publié le 24 April 2017. [Feuilleter le numéro spécial](http://besjournals.onlinelibrary.wiley.com/hub/issue/10.1111/%28ISSN%291365-2745.globalchangevirtualissue).

Les résultats de l'article ont été relayés dans plusieurs médias et rapports d'activités:
[The Conversation](https://t.co/pMXLUUrV0I),
[Le Figaro](/images/media/Figaro-16-02-2016.png),
[Radio Classique](http://www.radioclassique.fr/player/progaction/initPlayer/podcast/3-minutes-pour-la-planete-2016-02-16-06-48-50.html),
[Le Point](http://www.lepoint.fr/environnement/le-rechauffement-climatique-risque-d-empecher-les-forets-tropicales-de-stocker-le-carbone-12-02-2016-2017587_1927.php#xtor=RSS-221),
[FranceTV info](http://www.francetvinfo.fr/monde/environnement/le-rechauffement-climatique-risque-d-empecher-les-forets-tropicales-de-stocker-le-carbone_1312341.html#xtor=AL-54-%5Barticle%5D),
[El Mercurio](http://www.emol.com/noticias/Tecnologia/2016/02/12/788109/Estudio-asegura-que-cambio-climatico-amenaza-la-absorcion-de-CO2-por-bosques-tropicales.html),
[Midi-Libre](/images/media/MidiLibre-16-02-2016.png),
[Cirad](http://www.cirad.fr/en/news/all-news-items/press-releases/2016/climate-change-alters-the-co2-storage-capacity-of-tropical-forests),
[Cirad activity report 2015](http://www.cirad.fr/content/download/11005/128917/version/2/file/RA2015_FR.pdf).

## 2. Cartes historiques de la déforestation à Madagascar: soixante ans d'étude de la déforestation et de la fragmentation forestière.

Nous avons obtenu des cartes de suivi de la couverture forestière sans nuages à 30m de résolution sur la période 1990-2000-2010-2014 (Fig. XX)
qui sert de base au travail de modélisation du processus de déforestation. Ces cartes
constituent une première avancée par rapport aux cartes de déforestation actuellement
disponibles pour Madagascar qui présentent soit (i) une couverture nuageuse importante
[@ONE2013], soit (ii) une incertitude concernant les seuils de couverts arborés à
adopter pour définir la forêt sèche et épineuse à Madagascar [@Hansen2013], soit
(iii) une non prise en compte de la forêt sèche et épineuse en tant que forêt tropicale
[@Kim2014]. Ces cartes sont désormais disponibles sur le site du projet BioSceneMada:
\url{https://bioscenemada.cirad.fr/forestmaps}.

Ces cartes présentent l'évolution de la couverture des forêts _naturelles_ (hors
plantations) et ne prends pas en compte la régénération naturelle des forêts qui, même si
elle reste possible pour les forêts humides de l'est [@Saboureau1960,
  @Rasolofoharinoro1997], est limitée sur le long terme à Madagascar (succession de
régénérations et coupes ou brûlis) et conduit à des forêts secondaires ayant
potentiellement un niveau de biodiversité et de carbone moindre par rapport aux forêts
naturelles [@Grouzis2001]. Techniquement, nous sommes partis de la carte de couvert
forestier en 2000 à Madagascar issues des travaux de [@Harper2007]. Sur cette carte,
~200 000 hectares (ha) de nuages sont présents sur les ~4.2 millions d'hectares
(Mha) de forêt humide (4.8% de nuages). En utilisant la carte de couverture arborée
fournie par [@Hansen2013], nous avons remplacé les nuages par de la forêt si la
couverture arborée était supérieure à 75% [@Achard2014]. Cela nous a permis
d'obtenir une carte de couverture forestière sans nuages pour l'année 2000. En partant de
cette carte en 2000 et de la perte de couvert forestier annuel fournie par
[@Hansen2013], il a été possible d'obtenir des cartes d'évolution du couvert
forestier annuelle sur la période 2000-2010-2014. La carte de 1990 comprenait initialement très
peu de nuages (9603 ha). Compte tenu de ce fait, nous
n'avons considéré aucun changement de couverture forestière entre 1990 et 2000 sur ces
zones de nuage. Nous avons également corrigé la carte de 1990 en considérant que les
surfaces en forêt en 2000 l'étaient déjà en 1990. Des cartes supplémentaires pour les années _ca._ 1953, _ca._ 1973
[@Harper2007] et ont également été produites. La carte intiale de 1973 a été corrigée en considérant que les surfaces en forêt en
1990 l'étaient déjà en 1953 et 1973. L'ensemble de ces cartes permettent de retracer
l'évolution du couvert forestier à Madagascar sur une période d'environ 60 ans, de 1953 à
2014. 

**\underline{Vieilledent G.}, \underline{C. Grinand}, F. A. Rakotomalala, R. Ranaivosoa, \underline{J.-R. Rakotoarijaona}, \underline{T. F. Allnutt}, and F. Achard**. Combining global tree cover loss data with historical national forest-cover maps to look at six decades of deforestation and forest fragmentation in Madagascar. _bioRxiv_. 147827. doi: [10.1101/147827](https://doi.org/10.1101/147827).

## 3. Logiciel Python `deforestprob` pour le calcul de la probabilité spatiale de déforestation

Un module Python a été développé afin de pouvoir estimer rapidement la probabilité spatiale de déforestation sur de grandes échelles spatiales (nationales ou continentales) avec une résolution fine (ex. 30 ou 10 m) et de prédire quelles seront les zones à risques de déforestation et les zones potentielles de refuge de la biodiversité dans le futur. Le modèle portant sur la localisation de la déforestation permet de prédire la probabilité spatiale de déforestation en fonction de variables environnementales décrivant l'accessibilité de la forêt (distance aux routes, villages et rivières, distance à la lisière de la forêt, topographie), son statut de protection (appartenance au réseau d’aires naturelles protégées) et son historique (distance à la déforestation passée). Le module Python est disponible sur le serveur Github: <https://github.com/ghislainv/deforestprob>.

Nous avons utilisé ce module pour estimer la probabilité spatiale de déforestation à l'échelle nationale à Madagascar, à une résolution fine de 30 m et pour la couverture forestière de l'année 2010. Cette démarche a fait l'objet d'un tutoriel où chacune des étape de modélisation est indiquée pas à pas. Cet tutoriel, disponible sous forme d'un notebook Jupyter est disponible à l'adresse suivante: <https://ghislainv.github.io/deforestprob>. Le tutoriel pourra notamment être utilisé pendant les ateliers de renforcement de capacité dans les deux prochaines années à venir.

## 4. Modèles d'évolution de l'intensité de déforestation en Afrique et à Madagascar

## 4. Scénarios d'évolution de la couverture forestière à Madagascar et cartes du couvert forestier futur

## 5. MadaClim: portail de données climatiques et environnementales pour Madagascar.

Dans le cadre du projet BioSceneMada, nous avons développé le site internet MadaClim (<https://madaclim.cirad.fr>). Ce site reprend toutes les données climatiques actuelles fournies par WorldClim ainsi que les prédictions climatiques issues des modèles du GIEC (groupe d'experts intergouvernemental sur l'évolution du climat) et fournies par le CGIAR CCAFS. Les données sont recompilées (reprojetées et rééchantillonnées à 1km) et distribuées spécifiquement pour Madagascar. Des variables bioclimatiques supplémentaires comme l'évapotranspiration et le nombre de mois secs ont été calculées et ajoutées aux variables déjà disponibles. En plus des données climatiques, des données environnementales (sol, géologie, altitude, etc.) sont également fournies. Ce site et ces données sont particulièrement utiles pour tous les chercheurs, gestionnaires, membres d'ONG environnementales, ministères voulant étudier les effets du changement climatique à Madagascar. Elles peuvent être utilisées par exemple pour calculer les anomalies climatiques prédites par les modèles du GIECC.

## 6. Base de données de biodiversité à Madagascar

## 7. Atlas de la biodiversité à Madagascar et de sa vulnérabilité au changement climatique

## 8. Cartes de biodiversité et des communautés d'espèces à Madagascar

## 4. Communications:

- Sites webs: du projet BioSceneMada et des outils MadaClim et deforestprob
- Répertoires GitHub
- Communication des résultats de recherche sur les réseaux sociaux
- Conférences
- Présentations
- Rapports d'activités

