# 2. Résumé

```{r comment2, echo=FALSE}
# Résumé d'environ une à deux pages, destiné à être utilisé pour promouvoir les principaux résultats du projet auprès des utilisateurs et acteurs # socio-économiques intéressés. Il utilisera un vocabulaire non spécialiste, mais néanmoins précis.
```

Le projet FRB-FFEM BioSceneMada vise à produire des scénarios d'évolution de la biodiversité à Madagascar sous l'effet conjoint du changement climatique et de la déforestation d'origine anthropique (https://bioscenemada.cirad.fr). Le projet a une durée de 60 mois (36 mois consacrés au travail de recherche et 24 mois consacrés au transfert et à la communication des résultats auprès des gestionnaires de la biodiversité à Madagascar et des décideurs politiques). Démarré courant 2014, il s'est terminé en octobre 2019. Le projet associe quatre partenaires en France (Cirad, ETC Terra/Nitid\ae) et à Madagascar (WCS Madagascar, Office National de l'Environnement).

Madagascar est reconnu pour son exceptionnelle biodiversité, tant du point de vue du nombre d'espèces que des taux d'endémisme (proches de 90% dans tous les groupes taxonomiques). Cette biodiversité, principalement concentrée dans les forêts tropicales de l'île, est sévèrement menacée par le changement climatique et la déforestation. L'objectif du projet BioSceneMada est premièrement d'établir des scénarios de déforestation (en tenant compte notamment de la croissance démographique) et d'estimer la perte de biodiversité associée à ces scénarios. Deuxièmement, l'objectif est d'estimer l'impact des changements climatiques sur la perte de biodiversité. L'impact sur la biodiversité sera considéré sous l'angle des espèces (risque d'extinction des espèces via la restriction des aires de distribution, ex. les espèces de baobabs) mais également sous l'angle des communautés (perte d'habitat ou restriction des habitats pour les communautés, ex. la forêt épineuse). Troisièmement, l'objectif du projet est d'identifier les futurs points-chauds (_"hotspots"_) de biodiversité à fort risque de déforestation. Ces scénarios permettront notamment de réfléchir à l'optimisation du réseau d'aires naturelles protégées en concentrant les efforts de conservation sur des zones cibles identifiées sur la base de résultats scientifiques.

Les premiers résultats de recherche ont permis de proposer des scénarios de référence pour la déforestation à Madagascar à l'horizon 2050 et 2100. En s'appuyant sur l'étude de la déforestation passée (période 1990-2000-2010), les modèles prédisent une diminution du couvert forestier de 9.3 millions d'hectares (Mha) en 2010 à environ 5 Mha en 2050 et moins de 2 Mha en 2100. La déforestation se fait majoritairement en dehors des aires protégées jusqu'en 2050, puis pénètre dans les aires protégées au-delà de cette date. En 2100, la forêt résiduelle se situe en altitude dans des zones reculées (péninsule de Masoala).

Une base regroupant les données d'occurrence de 4969 espèces a également été constituée. Cette base regroupe des données animales (vertébrés et invertébrés) et végétales (arbres et autres plantes) pour une grande variété de groupes taxonomiques, représentatifs de la biodiversité à Madagascar. Cette base constitue un inventaire sans précédent de la biodiversité à Madagascar et regroupe des données vérifiées tant du point de vue taxonomique que de la localisation géographique. Ces données ont été utilisées pour modéliser la niche climatique des espèces et estimer leur vulnérabilité aux changements climatique. Les données issues des modèles climatiques du GIEC pour Madagascar ont été regroupées sur le site MadaClim (https://madaclim.cirad.fr) qui est un des produits du projet BioSceneMada. Un atlas comprenant les aires de distribution présentes et futures de l'ensemble des 4969 espèces sera édité. Cette analyse permettra d'identifier les hotspots présents et futurs de la biodiversité. A l'échelle de la communauté, ces données ont également été utilisées pour mettre en évidence l'effet du climat sur la structure des communautés. On montre notamment que l'importance du climat dans la détermination de l'assemblage des espèces est très variable d'un groupe taxonomique à l'autre.

Les résultats du projet montrent également que les forêts humides se situant en altitude, dans les zones peu accessibles (péninsule de Masoala notamment), et qui seront impactées tardivement par la déforestation, sont les plus sensibles au changement climatique. Les espèces de ces forêts sont en effet peu adaptées à une augmentation forte de la saisonnalité (impliquant une diminution de la saison de végétation) et à une augmentation forte de la température prévues dans cette région. Ainsi, la conservation de la forêt et de la biodiversité à Madagascar face à la double contrainte de la déforestation et du changement climatique constitue un véritable challenge. Au vue de ces résultats, la première action à entreprendre nous semble de lutter efficacement contre la déforestation afin de conserver les forêts naturelles existantes, qui ne représentent que 15% du territoire national à Madagascar en 2014. Nos résultats montrent également que ces actions de conservation ne pourront se mettre en place à Madagascar sans une meilleure orientation de l'aide internationale au développement avec pour objectif une amélioration de la gouvernance, une lutte contre la corruption et l'application ferme des lois environnementales. 
