# 3. Principaux résultats valorisés dans les publications scientifiques

```{r comment3, echo=FALSE}
# Un paragraphe de texte court (environ 500 caractères) par résultat marquant avec la référence de l'article.
```

## MadaClim: portail de données climatiques et environnementales à Madagascar

Nous avons développé le site internet MadaClim (<https://madaclim.cirad.fr>) qui reprend toutes les données climatiques actuelles ainsi que les prédictions climatiques issues des modèles du GIEC (groupe d'experts intergouvernemental sur l'évolution du climat). Les données ont été rééchantillonnées à 1km de résolution dans le système de projection WGS84 UTM 38S sur toute l'étendue de Madagascar. Des variables bioclimatiques comme l'évapotranspiration et le nombre de mois secs ont été recalculées et ajoutées aux variables existantes. En plus des données climatiques, des données environnementales incluant altitude, pente, irradiation solaire, géologie, sol, etc. ont été compilées.

_Références:_

Vieilledent G., O. Gardi, C. Grinand, C. Burren, M. Andriamanjato, C. Camara, C. J. Gardner, L. Glass, A. Rasolohery, H. Rakoto Ratsimba, V. Gond, and J.-R. Rakotoarijaona. 2016. Bioclimatic envelope models predict a decrease in tropical forest carbon stocks with climate change in Madagascar. _Journal of Ecology_. 104: 703-715. doi: https://doi.org/10.1111/1365-2745.12548.

Vieilledent G. MadaClim : a set of climatic and environmental spatial variables for Madagascar. Data paper. in prep.

## Carte de carbone forestier et vulnérabilité des forêts tropicales au changement climatique à Madagascar

En utilisant les données climatiques présentées précédemment et des données d'inventaires forestiers pour 1771 placettes réparties sur l'ensemble de Madagascar, nous avons démontré qu'il existait un lien fort entre climat et stocks de carbone forestiers. Nous avons produit une carte précise des stocks de carbone forestier en 2010 à Madagascar à une résolution de 250 m. Les changements climatiques devraient induire des modifications fortes des communautés forestières et en conséquence une diminution de -17% (7-24%) des stocks de carbone forestier à Madagascar à l'horizon 2100 par rapport à 2010.

_Références:_

Vieilledent G., O. Gardi, C. Grinand, C. Burren, M. Andriamanjato, C. Camara, C. J. Gardner, L. Glass, A. Rasolohery, H. Rakoto Ratsimba, V. Gond, and J.-R. Rakotoarijaona. 2016. Bioclimatic envelope models predict a decrease in tropical forest carbon stocks with climate change in Madagascar. _Journal of Ecology_. 104: 703-715. doi: https://doi.org/10.1111/1365-2745.12548.

El Hajj M., N. Baghdadi, I. Fayad, G. Vieilledent, J.-S. Bailly, and D. Ho Tong Minh. 2017. Interest of integrating spaceborne LiDAR data to improve the estimation of biomass in high biomass forested areas. _Remote Sensing_. 9(3). https://doi.org/10.3390/rs9030213.

Ho Tong Minh D., E. Ndikumana, G. Vieilledent, D. McKey and N. Baghdadi. 2018. Potential value of combining ALOS PALSAR and Landsat-derived tree cover data for forest biomass retrieval in Madagascar. _Remote Sensing of Environment_. 213: 206-214. https://doi.org/10.1016/j.rse.2018.04.056.

Grinand C., G. Le Maire, G. Vieilledent, H. Razakamanarivo, T. Razafimbelo, and M. Bernoux. 2017. Estimating temporal changes in soil carbon stocks at the ecoregional scale in Madagascar using remote-sensing. _International Journal of Applied Earth Observation and Geoinformation_. 54: 1-14. https://doi.org/10.1016/j.jag.2016.09.002.

## Base de données de biodiversité à Madagascar

Nous avons construit un jeu de données sur la biodiversité à Madagascar regroupant 300 000 observations (points de présence) pour 4969 espèces. Ces espèces sont réparties dans différents groupes taxonomiques (Plantes, Vertébrés, Invertébrés) et sont représentatives de la biodiversité à Madagascar. Ces données, provenant de différents instituts, sont issues d'un travail de prospection conséquent qui s'étale sur plusieurs dizaines d'années. L'acquisition de ces nouvelles données ont permis d'enrichir la base de données REBIOMA (Réseau de la Biodiversité de Madagacar, http://data.rebioma.net) hébergée par le WCS, partenaire du projet BioSceneMada.

_Référence:_

Charra M. 2015. Création d'une base de données et modélisation de la biodiversité à Madagascar. Rapport de Master. Sous la direction de G. Vieilledent. Master II Ecologie, Biodiversité, Evolution (EBE), Préservation et Gestion Conservatoire des Ecosystèmes. Université Paris-Saclay ENS, Université Paris Sud, AgroParisTech, Sorbonne Université, MNHN. 32 p.

## Prototype d'atlas de la biodiversité à Madagascar et de sa vulnérabilité au changement climatique

Nous avons développé le package R `speciesatlas` (https://github.com/ghislainv/speciesatlas) permettant de modéliser la niche climatique des espèces à partir de modèles d'ensemble [@Vieilledent2013a; @Araujo2007a]. Le script permet d'estimer l'aire de distribution actuelle et future des espèces à Madagascar. En utilisant cette approche pour les 4969 espèces du jeu de données sur la biodiversité à Madagascar, l'idée est d'obtenir un atlas de la biodiversité à Madagascar et de sa vulnérabilité au changement climatique. Un prototype de cet atlas a été réalisé pour les 7 espèces de baobabs présentes à Madagascar (https://bioscenemada.cirad.fr/FileTransfer/atlas.pdf) et 55 des 111 espèces de lémuriens connues à Madagascar (https://etclab.org/atlas).

_Références:_

Muniz Tagliari M., P. Danthu, J.-M. Leong Pock Tsy, C. Cornu, J. Lenoir, V. Carvalho-Rocha, G. Vieilledent. Not all species will migrate polewards as the climate warms: the case of the seven baobab species in Madagascar. submitted.

Knoplock C. 2019. The importance of deforestation and climate change in shaping lemurs' distributions and identifying their areas of climatic refuges. Rapport de Master. Sous la direction de C. Grinand et G. Vieilledent. Master Biodiversité, Ecologie et Evolution (BEE), finalité Gestion Adaptative de la Biodiversité (GABI). Université d'Aix Marseille. 43 p.

Colas A. 2018. Creation of a biodiversity atlas for Madagascar with the `speciesatlas` R package. Rapport de Master. Sous la direction de C. Grinand et G. Vieilledent. Master Bioinformatique et modélisation (BIM). INSA Lyon. 29 p.

Vieilledent G., C. Knoplock, A. Colas, and C. Grinand. Atlas of the biodiversity of Madagascar: present species distribution and species vulnerability to climate change. in prep.

## Toutes les espèces ne devraient pas migrer vers les pôles sous l'effet du réchauffement climatique: le cas des 7 espèces de baobabs à Madagascar.

Nous avons étudié l'impact du changement climatique sur les 7 espèces de baobabs présentes à Madagascar. Nous avons utilisé un vaste jeu de données d'occurrence issu d'un travail de prospection sur le terrain et d'analyse d'images satellites pour modéliser la niche climatique et expliquer la répartition des sept espèces de baobabs (genre _Adansonia_) à Madagascar. Nous avons identifié les variables bioclimatiques les plus importantes expliquant la distribution de chacune des espèces. En utilisant les projections climatiques du GIECC, nous avons prédit la distribution future probable de chaque espèce et son risque d'extinction estimée à partir de la contraction de l'aire de distribution de l'espèce. Nous avons également expliqué les changements d'aire de distribution des espèces en examinant l'importance relative des variables climatiques dans la détermination de la niche climatique des espèces et les anomalies climatiques dans le future. Nous avons montré que trois espèces de baobabs connaîtront une forte contraction de leur aire de distribution ($>=-50\%$) dans un scénario où la dispersion de l'espèce est supposée possible (hypothèse conservatrice). Si la contraction de l'aire de distribution de l'espèce _A. rubrostipa_ s'explique par une augmentation du déficit hydrique, la contraction de l'aire de distribution des deux espèces _A. perrieri_ et _A. suarezensis_ s'explique par une augmentation de la saisonnalité de la température et une impossibilité de se déplacer vers des zones à saisonnalité plus faible (vers l'équateur) en raison de l'océan qui agit comme une barrière géographique. Dans les zones tropicales, il est fortement probable que de nombreuses espèces soient adaptées à une saisonnalité faible et vulnérables à une augmentation probable de la saisonnalité sous l'ensemble des tropiques. L'équateur pourrait ainsi constituer une barrière climatique forte pour les espèces tropicales. Dans l'océan Indien et en Asie du Sud-Est, comme à Madagascar, les espèces pourraient ne pas pouvoir se déplacer vers l'équateur, l'océan agissant comme une barrière géographique.

_Référence:_

Muniz Tagliari M., P. Danthu, J.-M. Leong Pock Tsy, C. Cornu, J. Lenoir, V. Carvalho-Rocha, G. Vieilledent. Not all species will migrate polewards as the climate warms: the case of the seven baobab species in Madagascar. submitted.

## Vulnérabilité des espèces de lémuriens au changement climatique et à la déforestation à Madagascar: vers une conservation des zones de refuge climatique

Nous avons étudié l'impact du changement climatique et de la déforestation à Madagascar pour 55 des 111 espèces de lémuriens connues à Madagascar à l'aide du package `speciesatlas`. La base de données de présence inclut des informations pour 88 espèces de lémuriens mais seules 55 espèces avaient un nombre de données suffisant pour la modélisation de la niche. Les résultats montrent que le changement climatique devrait diminuer l'habitat des lémuriens de plus de 60% en moyenne. En comparaison, la déforestation seule contribuerait à une diminution de 50% de l'habitat. Ces résultats signifient que si les lémuriens sont incapables de s'adapter au changement climatique, alors ce dernier sera plus néfaste pour eux que la déforestation. Par conséquent, il semble important de conserver en priorité les sites les plus climatiquement stables. Nous avons donc identifié ces zones de refuges climatiques et produit une carte à l'échelle de Madagascar. Ces résultats ont été également analysés au regard du réseau d'aires protégées actuel. Il apparaît ainsi que plus de 55% des refuges climatiques sont à l'extérieur du réseau d'aires protégées. Cela souligne la nécessité de développer davantage le réseau d'aires protégées actuel. De plus, 75% de ces refuges sont fortement menacés par la déforestation.

_Référence:_

Knoplock C.. 2019. The importance of deforestation and climate change in shaping lemurs' distributions and identifying their areas of climatic refuges. Rapport de Master. Sous la direction de C. Grinand et G. Vieilledent. Master Biodiversité, Ecologie et Evolution (BEE), finalité Gestion Adaptative de la Biodiversité (GABI). Université d'Aix Marseille. 43 p.

## Cartes de biodiversité et des communautés d'espèces à Madagascar

En utilisant des modèles de communautés [@Ferrier2007], nous avons cherché à identifier les facteurs environnementaux déterminants les assemblages d'espèces. Ces facteurs peuvent être climatiques ou associés à des barrières géographiques comme les bassins versants ou les rivières [@Pearson2009]. En appliquant ce modèle à nos données de présence d'espèces à Madagascar, nous avons obtenu une première carte de la biodiversité $\beta$ à Madagascar. Mais le pourcentage de déviance expliquée par le modèle est faible (<10%). En appliquant ce même modèle à chaque groupe taxonomique, nous avons trouvé que les facteurs expliquants l'assemblage des communautés d'espèces varient d'un groupe taxonomique à l'autre, le climat n'étant pas toujours le facteur le plus important. Pour le groupe des lémuriens, ce sont les bassins versants qui expliquent en majorité l'assemblage des espèces. A contrario, le climat explique une grande partie des assemblages d'espèces de reptiles et d'amphibiens, espèces poïkilothermes (animaux ayant une température corporelle qui varie avec celle de leur milieu). Pour d'autres groupes, comme les arbres, les facteurs climatiques et les bassins versants semblent expliquer à part égale les assemblages d'espèces.

_Référence:_

Charra M.. 2015. Création d'une base de données et modélisation de la biodiversité à Madagascar. Rapport de Master. Sous la direction de G. Vieilledent. Master Ecologie, Biodiversité, Evolution, Préservation et Gestion
Conservatoire des Ecosystèmes. Université Paris-Saclay ENS, Université Paris Sud, AgroParisTech, Sorbonne Université, MNHN. 32 p.

## Soixante ans (1953-2014) d'étude de la déforestation et de la fragmentation forestière à Madagascar

Nous avons obtenu de nouvelles cartes d'évolution de la couverture forestière à Madagascar sur la période 2000-2014. Elles viennent compléter les cartes de @Harper2007 pour les années 1953, 1973 et 1990. Nous montrons que le couvert forestier a diminué de 44% sur la période 1953-2014. Les forêts naturelles couvrent 8.9 Mha en 2014 (15% du territoire national) et incluent 4.4 Mha (50%) de forêt humide, 2.6 Mha (29%) de forêt sèche, 1.7 Mha de forêt épineuse (19%) et environ 177,000 ha (2%) de mangrove. Depuis 2005, les surfaces déforestées annuellement ont augmenté à Madagascar pour atteindre 100 000 ha/an sur la période 2010-2014. Aujourd'hui, environ 50% de la forêt est située à moins de 100 m de la lisière et est donc fortement exposée aux perturbations.

Le président malgache M. Andry Rajoelina a cité les résultats de cette étude début 2019 dans une communication à son conseil des ministres pour le lancement d'un plan national de reforestation et de conservation des forêts à Madagascar (https://ecology.ghislainv.fr/images/media/Foret_Andry_Rajoelina.pdf). Il a rappelé les chiffres de la déforestation et officialisé le lancement de ce plan lors du One Planet Summit en mars 2019 à Nairobi (https://www.youtube.com/watch?v=NWpcDegsv0Y).

_Référence:_

Vieilledent G., C. Grinand, F. A. Rakotomalala, R. Ranaivosoa, J.-R. Rakotoarijaona, T. F. Allnutt, and F. Achard. 2018. Combining global tree cover loss data with historical national forest-cover maps to look at six decades of deforestation and forest fragmentation in Madagascar. _Biological Conservation_. 222: 189-197. https://doi.org/10.1016/j.biocon.2018.04.008.

## Retour sur les facteurs de déforestation: la pauvreté n'est pas l'unique responsable de la déforestation à Madagascar 

A l'issue d'une mission de terrain dans le Menabe, à l'ouest de Madagascar, nous avons conclu que les causes directes de la déforestation dans la région sont l'agriculture sur brûlis pour la culture de rente comme le maïs ou l'arachide. Le maïs et l'arachide sont principalement exportés sur les marchés internationaux. Ces activités sont favorisées par un marché global non régulé, une forte corruption et une non-application des lois environnementales à Madagascar. Si aucune solution n'est trouvée pour lutter efficacement contre la déforestation, le couvert forestier pourrait diminuer de plus de 50% sur la période 2010-2050 dans la région.

_Référence:_

Vieilledent G., M. Nourtier, C. Grinand, M. Pedrono, A. Clausen, T. Rabetrano, J.-R. Rakotoarijaona, B. Rakotoarivelo, F. A. Rakotomalala, L. Rakotomalala, A. Razafimpahanana, J. M. Ralison, and F. Achard. It's not only poverty: uncontrolled global trade and bad governance are responsible for unceasing deforestation in Western Madagascar. pre-print.

## Cartes du couvert forestier futur à Madagascar

Nous avons estimé la probabilité spatiale de déforestation à l'échelle nationale à Madagascar, à une résolution fine de 30 m pour l'année 2010. A partir de cette carte, en considérant une déforestation moyenne annuelle de 100 000 ha/an, nous avons pu prédire les zones susceptibles d'être déforestées sur la période 2010-2050. Les projections montrent une concentration des forêts dans les zones peu accessibles et situées en altitude dans le futur. Les aires protégées semblent relativement efficaces sur le court terme (horizon 2050) en contribuant à déplacer la déforestation sur des zones à plus faible biodiversité, en dehors des aires protégées mais n'ont pas d'efficacité sur le plus long terme (horizon 2100).

\newpage
_Références:_

Dezécache C., J.-M. Salles, G. Vieilledent, and B. Hérault. 2017. Moving forward socio-economically focused models of deforestation. _Global Change Biology_. 23(9): 3484-3500. https://doi.org/10.1111/gcb.13611.

Grinand C., Vieilledent G., T. Razafimbelo, J.-R. Rakotoarijaona, M. Nourtier, and M. Bernoux. Landscape‐scale spatial modelling of deforestation, land degradation and regeneration using machine learning tools. _Land Degradation and Development_. in press. https://doi.org/10.1002/ldr.3526.

Vieilledent G., and F. Achard. Including spatial-autocorrelation in deforestation model to obtain realistic deforestation projections at national or continental scales. in prep.

Knoplock C.. 2019. The importance of deforestation and climate change in shaping lemurs' distributions and identifying their areas of climatic refuges. Rapport de Master. Sous la direction de C. Grinand et G. Vieilledent. Master Biodiversité, Ecologie et Evolution (BEE), finalité Gestion Adaptative de la Biodiversité (GABI). Université d'Aix Marseille. 43 p.

## Modèles d'évolution de l'intensité de déforestation en Afrique et à Madagascar

Nous avons établi un modèle d'évolution des surfaces déforestées pour les pays africains en prenant en compte le couvert forestier existant et la taille de la population. Ce modèle est utilisé pour prédire les tendances de déforestation pour l'Afrique pays par pays. Pour Madagascar, on observerait une diminution de l'intensité de déforestation après 1950 liée à la transition démographique et à la réduction du couvert forestier disponible. Toutefois, les surfaces déforestées annuellement resteraient importantes (> 75 000 ha/an). Selon ce scénario, le couvert forestier diminuerait ainsi de plus de 50% entre 2000 et 2050 et de plus de 75% entre 2000 et 2100, pour atteindre environ 2 Mha en 2100 (Fig. 9).

_Référence:_

Vieilledent G., W. F. Laurance, S. Peedell, and F. Achard. The fate of tropical forests associated to the demographic explosion in Africa. in prep.
