# 6. Accès aux données

```{r comment11, echo=FALSE}
# Merci d'indiquer les bases de données créées ou alimentées par le projet, ainsi que les conditions d'accès à ces données.
```

## Données

Un effort a été entrepris afin que les données du projet BioSceneMada suivent les principes FAIR (Faciles à trouver, Accessibles, Interopérables et Réutilisables). En plus des sites web, deux plateformes ont été utilisées dans le cadre du projet BioSceneMada pour le dépôt de données et la création de DOIs ("data object identifier"). Nous avons utilisé la plateforme Dryad (https://datadryad.org) et la plateforme Dataverse du Cirad (https://dataverse.cirad.fr), mise en place plus récemment (Février 2018):

- Base de données climatiques et environnementales MadaClim accessible via le site internet https://madaclim.cirad.fr.
- Base de données de biodiversité: http://data.rebioma.net.
- Carte des stocks de carbone forestier sur le site internet du projet à l'adresse https://bioscenemada.cirad.fr/carbonmaps, ainsi que sur la plateforme Dryad https://doi.org/10.5061/dryad.9ph68 (567 téléchargements au 16/01/2020).
- Cartes de couverture forestière sur la période 1953-2017 accessibles sur le site internet du projet à l'adresse https://bioscenemada.cirad.fr/forestmaps, ainsi que sur le Dataverse Cirad https://doi.org/10.18167/DVN1/AUBRRC (8157 téléchargements au 16/01/2020).
- Carte de probabilité de déforestation en 2010 sur le site du projet: https://bioscenemada.cirad.fr/forestmaps et https://forestatrisk.cirad.fr/mada
- Carte de couvert forestier futur pour l'année 2050: https://forestatrisk.cirad.fr/mada

Concernant la base de données de biodiversité, les données qu'elle inclue proviennent d'institutions différentes qui ont accepté de les partager dans le cadre du projet BioSceneMada. Seule une partie de ces données brutes sont accessibles publiquement via la base de données ReBioMa maintenue par le WCS Madagascar. Une discussion avec l'ensemble des institutions ayant fourni les données de biodiversité est en cours afin de voir dans quelle mesure celles-ci peuvent être rendues publiques.

## Scripts informatiques

La plupart des scripts informatiques ayant servi à l'obtention des résultats sont également mis à la disposition de la communauté scientifique et des gestionnaires. L'outil utilisé pour le partage du code est la plateforme GitHub. Comme pour les données, d'autres répertoires seront créés et rendus publics au fur et à mesure de la publication des articles en préparation.

- Code pour les données climatiques et environnementales: https://github.com/ghislainv/madaclim
- Code du module Python `forestatrisk`: https://github.com/ghislainv/forestatrisk
- Code du package R `speciesatlas`: https://github.com/ghislainv/speciesatlas
- Code du package R `jSDM`: https://github.com/ghislainv/jSDM
- Code pour les stocks de carbone forestiers: https://github.com/ghislainv/carbonmap
- Code pour les cartes historiques de déforestation sur la période 1953-2017: https://github.com/ghislainv/deforestation-maps-Mada
- Code pour la carte de probabilité de déforestation et la carte de couvert forestier en 2050: https://github.com/ghislainv/forestatrisk-tutorial
- Code pour l'analyse de la déforestation dans le Menabe: https://github.com/ghislainv/menabe
